name = "foodq-api-router"
compatibility_date = "2024-08-13"
main = "api-proxy-worker.js"

# Custom domain configuration for api.foodqapp.com
[env.production]
routes = [
  { pattern = "api.foodqapp.com/*", custom_domain = true }
]

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

# Supabase configuration (same as main app)
SUPABASE_URL = "https://zobhorsszzthyljriiim.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYmhvcnNzenp0aHlsanJpaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODIzNzYsImV4cCI6MjA2OTU1ODM3Nn0.91GlHZxmJGg5E-T2iR5rzgLrQJzNPNW-SzS2VhqlymA"

# Google Places API (for location services)
# GOOGLE_PLACES_API_KEY = "your-google-places-api-key"

# OpenAI API (for food generation)
# OPENAI_API_KEY = "your-openai-api-key"

[build]
command = ""

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }