name = "foodq-api-proxy"
compatibility_date = "2024-08-13"
main = "api-proxy-worker.js"

# Custom domain configuration for api.foodqapp.com
[env.production]
routes = [
  { pattern = "api.foodqapp.com/*", custom_domain = true }
]

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"