# Cloudflare Pages configuration for FoodQ
name = "foodq"
compatibility_date = "2024-09-23" 
compatibility_flags = ["nodejs_compat"]

# Pages Functions configuration
pages_build_output_dir = "dist"

# R2 Storage for Food Images
[[r2_buckets]]
binding = "FOOD_IMAGES"
bucket_name = "foodq-images"

# Default environment variables for Functions (development) - NOENCIRCLES PATTERN: Production Auth + Local API
[vars]
NODE_ENV = "development"
ENVIRONMENT = "local"
# Production Supabase for JWT validation (NoenCircles pattern)
SUPABASE_URL = "https://zobhorsszzthyljriiim.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYmhvcnNzenp0aHlsanJpaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODIzNzYsImV4cCI6MjA2OTU1ODM3Nn0.91GlHZxmJGg5E-T2iR5rzgLrQJzNPNW-SzS2VhqlymA"
# Local Supabase service role for database operations
LOCAL_SUPABASE_URL = "http://127.0.0.1:58321"
LOCAL_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
DATABASE_URL = "postgresql://postgres:postgres@127.0.0.1:58322/postgres"
API_KEY = "test-api-key-2024"
# Google Places API key - Replace with your actual API key
GOOGLE_PLACES_API_KEY ="AIzaSyDWZXwJ2DaQMkWlVuBjk6WzAFh6Dqqa8cY"

# Production environment
[env.production]
[[env.production.r2_buckets]]
binding = "FOOD_IMAGES"
bucket_name = "foodq-images"

[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"
SUPABASE_URL = "https://zobhorsszzthyljriiim.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYmhvcnNzenp0aHlsanJpaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODIzNzYsImV4cCI6MjA2OTU1ODM3Nn0.91GlHZxmJGg5E-T2iR5rzgLrQJzNPNW-SzS2VhqlymA"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYmhvcnNzenp0aHlsanJpaWltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzk4MjM3NiwiZXhwIjoyMDY5NTU4Mzc2fQ.bH-ROAAkSODqVzjoofUmEfV3WrYQqJcsg68Ad4fbvRU"
GOOGLE_PLACES_API_KEY ="AIzaSyDWZXwJ2DaQMkWlVuBjk6WzAFh6Dqqa8cY"
API_KEY = "test-api-key-2024"
# OPENAI_API_KEY should be set as a Cloudflare secret, not in this file
# Run: npx wrangler secret put OPENAI_API_KEY