# Cloudflare Pages configuration for GraBeat
name = "grabeat"
compatibility_date = "2024-09-23" 
compatibility_flags = ["nodejs_compat"]

# Pages Functions configuration
pages_build_output_dir = "dist"

# Default environment variables for Functions (development) - NOENCIRCLES PATTERN: Production Auth + Local API
[vars]
NODE_ENV = "development"
ENVIRONMENT = "local"
# Production Supabase for JWT validation (NoenCircles pattern)
SUPABASE_URL = "https://zobhorsszzthyljriiim.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYmhvcnNzenp0aHlsanJpaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODIzNzYsImV4cCI6MjA2OTU1ODM3Nn0.91GlHZxmJGg5E-T2iR5rzgLrQJzNPNW-SzS2VhqlymA"
# Local Supabase service role for database operations
LOCAL_SUPABASE_URL = "http://127.0.0.1:58321"
LOCAL_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
DATABASE_URL = "postgresql://postgres:postgres@127.0.0.1:58322/postgres"
API_KEY = "test-api-key-2024"

# Production environment
[env.production.vars]
NODE_ENV = "production"
ENVIRONMENT = "production"
# Production Supabase credentials will be set in Cloudflare Pages
SUPABASE_URL = "https://zobhorsszzthyljriiim.supabase.co"
SUPABASE_ANON_KEY = "production-anon-key"
SUPABASE_SERVICE_ROLE_KEY = "production-service-role-key"