name: foodq
description: "FoodQ - Direct Food Items at Discount Prices"
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Backend Integration
  supabase_flutter: ^2.5.6
  http: ^1.5.0
  app_links: ^6.4.0
  
  # Authentication handled by Supabase OAuth

  # Firebase (temporarily disabled for initial setup)
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10

  # Payment
  stripe_android: ^10.1.0
  stripe_ios: ^10.1.0

  # Location Services with Google Maps
  geolocator: ^10.1.0
  location: ^5.0.3
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.0.9

  # Navigation
  go_router: ^12.1.3

  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.2.2
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Professional UI packages
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.0

  # Overflow debugging and responsive design
  flutter_layout_grid: ^2.0.5
  responsive_framework: ^1.4.0

  # Image handling
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  
  # QR Code generation and scanning
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Additional UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Testing
  patrol: ^3.6.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  
  # Code Generation
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # UI Testing
  golden_toolkit: ^0.15.0
  alchemist: ^0.7.0

  # Linting
  flutter_lints: ^3.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
